// ===========================================
// Laura Tejeda — Content (ES / EN)
// ===========================================

export const CONTENT  = {
  brand: {
    name: "Laura Tejeda",
    initials: "LT",
    location: "Barranquilla, Colombia",
    email: "estudio@lauratejeda.co",
    phone: "+57 300 000 0000",
    instagram: "@laura.tejeda.estudio",
    pinterest: "lauratejedaestudio",
  },

  copy: {
    es: {
      tagline: "Arquitecta e interiorista",
      heroLine1: "Espacios",
      heroLine2: "que respiran",
      heroLine3: "el Caribe",
      heroSub: "Estudio independiente de arquitectura e interiorismo, fundado en Barranquilla. Trabajamos con materiales locales, luz natural y la lentitud que pide cada lugar.",
      navHome: "Inicio",
      navArch: "Arquitectura",
      navInt: "Interiorismo",
      navAbout: "Estudio",
      navServices: "Servicios",
      navContact: "Contacto",

      featuredEyebrow: "Selección",
      featuredTitle: "Proyectos destacados",
      featuredAll: "Ver todos los proyectos",

      indexEyebrow: "Trabajo",
      indexArchTitle: "Arquitectura",
      indexArchSub: "Casas, pabellones y obra nueva en el Caribe colombiano.",
      indexIntTitle: "Interiorismo",
      indexIntSub: "Apartamentos, restaurantes y espacios comerciales con una lectura cálida del lugar.",

      manifestoEyebrow: "Manifiesto",
      manifestoTitle: "Construir despacio, habitar bien.",
      manifestoBody: "Creemos en una arquitectura paciente: la que escucha al clima antes que a la moda, prefiere la madera con vetas a las superficies perfectas, y entiende que una casa se termina de hacer con el tiempo. Cada proyecto empieza con una conversación larga y un cuaderno.",

      aboutEyebrow: "Sobre Laura",
      aboutTitle: "Una arquitecta del Caribe, formada entre Bogotá y Lisboa.",
      aboutBody1: "Laura Tejeda (Barranquilla, 1991) es arquitecta de la Universidad de los Andes y magíster en Diseño de Interiores por la Faculdade de Arquitectura de Lisboa. Antes de fundar su estudio en 2020, trabajó en oficinas en Cartagena, Ciudad de México y Oporto.",
      aboutBody2: "Su práctica se mueve entre la arquitectura residencial costera y el interiorismo de pequeña escala. Le interesan los climas tropicales, la cerámica artesanal, las celosías, y la manera en que las casas viejas del Caribe respiran sin pedir aire acondicionado.",
      aboutBody3: "Ha sido reconocida por la Bienal Colombiana de Arquitectura (mención en vivienda, 2023) y publicada en revistas como Axxis, Diseño Interior y Wallpaper* Latinoamérica.",

      servicesEyebrow: "Qué hacemos",
      servicesTitle: "Servicios",
      servicesIntro: "Trabajamos por encargo, con un equipo pequeño y un calendario que respeta los tiempos del oficio.",

      processEyebrow: "Proceso",
      processTitle: "Cómo trabajamos",
      processIntro: "Cuatro etapas, sin atajos. Cada una con su entregable y su conversación.",

      contactEyebrow: "Hablemos",
      contactTitle: "¿Tienes un proyecto en mente?",
      contactBody: "Cuéntanos sobre el lugar, el programa y los tiempos. Respondemos en menos de tres días hábiles.",
      contactNamePlaceholder: "Tu nombre",
      contactEmailPlaceholder: "Correo electrónico",
      contactSubjectPlaceholder: "Tipo de proyecto",
      contactMessagePlaceholder: "Cuéntanos sobre tu proyecto, el lugar, los plazos…",
      contactSend: "Enviar mensaje",
      contactSent: "Mensaje enviado. Gracias.",

      footerNote: "Estudio de arquitectura e interiorismo. Barranquilla, Colombia.",
      footerRights: "Todos los derechos reservados.",

      detailLocation: "Ubicación",
      detailYear: "Año",
      detailType: "Tipología",
      detailArea: "Área",
      detailStatus: "Estado",
      detailRole: "Rol",
      detailTeam: "Equipo",
      detailPhotos: "Fotografía",
      detailNext: "Siguiente proyecto",
      detailBack: "Volver",
      detailGallery: "Galería",
      detailAbout: "Sobre el proyecto",

      filterAll: "Todos",
      filterResidential: "Residencial",
      filterCommercial: "Comercial",
      filterCultural: "Cultural",

      ctaSchedule: "Agendar conversación",
      ctaViewProject: "Ver proyecto",
    },

    en: {
      tagline: "Architect & interior designer",
      heroLine1: "Spaces",
      heroLine2: "that breathe",
      heroLine3: "the Caribbean",
      heroSub: "Independent architecture and interior design studio, based in Barranquilla. We work with local materials, daylight, and the patience each place asks for.",
      navHome: "Home",
      navArch: "Architecture",
      navInt: "Interiors",
      navAbout: "Studio",
      navServices: "Services",
      navContact: "Contact",

      featuredEyebrow: "Selection",
      featuredTitle: "Featured projects",
      featuredAll: "View all projects",

      indexEyebrow: "Work",
      indexArchTitle: "Architecture",
      indexArchSub: "Houses, pavilions and new builds across the Colombian Caribbean.",
      indexIntTitle: "Interiors",
      indexIntSub: "Apartments, restaurants and retail with a warm reading of place.",

      manifestoEyebrow: "Manifesto",
      manifestoTitle: "Build slowly, inhabit well.",
      manifestoBody: "We believe in patient architecture: the kind that listens to climate before fashion, prefers grained timber over perfect surfaces, and understands that a house is finished by time itself. Every project starts with a long conversation and a notebook.",

      aboutEyebrow: "About Laura",
      aboutTitle: "A Caribbean architect, trained between Bogotá and Lisbon.",
      aboutBody1: "Laura Tejeda (Barranquilla, 1991) holds a degree in Architecture from Universidad de los Andes and a Master's in Interior Design from Faculdade de Arquitectura de Lisboa. Before founding her studio in 2020, she worked in offices in Cartagena, Mexico City and Porto.",
      aboutBody2: "Her practice moves between coastal residential architecture and small-scale interiors. She is drawn to tropical climates, handmade ceramics, latticework, and the way old Caribbean houses breathe without ever asking for air conditioning.",
      aboutBody3: "She has been recognised by the Colombian Architecture Biennial (housing mention, 2023) and published in Axxis, Diseño Interior and Wallpaper* Latin America.",

      servicesEyebrow: "What we do",
      servicesTitle: "Services",
      servicesIntro: "We work by commission, with a small team and a calendar that respects the rhythm of craft.",

      processEyebrow: "Process",
      processTitle: "How we work",
      processIntro: "Four stages, no shortcuts. Each with its deliverable and its conversation.",

      contactEyebrow: "Let's talk",
      contactTitle: "Have a project in mind?",
      contactBody: "Tell us about the place, the brief and the timing. We reply within three working days.",
      contactNamePlaceholder: "Your name",
      contactEmailPlaceholder: "Email",
      contactSubjectPlaceholder: "Project type",
      contactMessagePlaceholder: "Tell us about your project, the place, timelines…",
      contactSend: "Send message",
      contactSent: "Message sent. Thank you.",

      footerNote: "Architecture and interior design studio. Barranquilla, Colombia.",
      footerRights: "All rights reserved.",

      detailLocation: "Location",
      detailYear: "Year",
      detailType: "Type",
      detailArea: "Area",
      detailStatus: "Status",
      detailRole: "Role",
      detailTeam: "Team",
      detailPhotos: "Photography",
      detailNext: "Next project",
      detailBack: "Back",
      detailGallery: "Gallery",
      detailAbout: "About the project",

      filterAll: "All",
      filterResidential: "Residential",
      filterCommercial: "Commercial",
      filterCultural: "Cultural",

      ctaSchedule: "Schedule a call",
      ctaViewProject: "View project",
    },
  },

  // ============== PROJECTS ==============
  projects: [
    // -------- ARCHITECTURE --------
    {
      id: "casa-palmar",
      category: "architecture",
      featured: true,
      tone: "warm",
      title: { es: "Casa Palmar", en: "Palmar House" },
      subtitle: {
        es: "Una casa de patios para vivir con el viento del norte.",
        en: "A courtyard house to live with the northern breeze.",
      },
      location: "Puerto Colombia, Atlántico",
      year: "2024",
      type: { es: "Vivienda unifamiliar", en: "Single-family house" },
      area: "320 m²",
      status: { es: "Construido", en: "Built" },
      role: { es: "Arquitecta principal", en: "Lead architect" },
      team: { es: "Laura Tejeda, Mateo Ríos, Valentina Cárdenas", en: "Laura Tejeda, Mateo Ríos, Valentina Cárdenas" },
      photos: "Federico Ríos",
      about: {
        es: "Casa Palmar nace de una pregunta simple: cómo habitar el calor sin huir de él. Tres patios escalonados ordenan la planta — uno de bienvenida, uno de agua y uno de sombra — y permiten que la brisa del norte cruce la casa entera. Los muros de bahareque encalado, la madera de roble local y la cerámica artesanal de Galapa componen una paleta que envejece bien.",
        en: "Palmar House began with a simple question: how to inhabit heat without escaping it. Three stepped courtyards organise the plan — a welcome court, a water court, a shade court — and let the northern breeze cross the entire house. Limewashed bahareque walls, local oak and handmade ceramics from Galapa make a palette that ages well.",
      },
      gallery: [
        { tone: "warm", caption: { es: "Patio de bienvenida visto desde la entrada", en: "Welcome courtyard seen from the entrance" } },
        { tone: "cream", caption: { es: "Galería sur con celosía de madera", en: "South gallery with timber latticework" } },
        { tone: "terracotta", caption: { es: "Detalle de cerámica artesanal", en: "Handmade ceramic detail" } },
        { tone: "stone", caption: { es: "Sala principal — vista al patio del agua", en: "Main living room — view to the water court" } },
        { tone: "dark", caption: { es: "Atardecer desde el corredor norte", en: "Dusk from the northern gallery" } },
        { tone: "warm", caption: { es: "Cocina con encimera en piedra de Tubará", en: "Kitchen with Tubará stone counter" } },
      ],
    },
    {
      id: "pabellon-mangle",
      category: "architecture",
      featured: true,
      tone: "olive",
      title: { es: "Pabellón Mangle", en: "Mangrove Pavilion" },
      subtitle: {
        es: "Una pieza pequeña, levantada sobre pilotes de madera.",
        en: "A small piece, lifted on timber stilts.",
      },
      location: "Tierrabomba, Bolívar",
      year: "2023",
      type: { es: "Pabellón cultural", en: "Cultural pavilion" },
      area: "85 m²",
      status: { es: "Construido", en: "Built" },
      role: { es: "Arquitecta principal", en: "Lead architect" },
      team: { es: "Laura Tejeda con Carpintería Caribe", en: "Laura Tejeda with Carpintería Caribe" },
      photos: "Andrés Valbuena",
      about: {
        es: "Encargado por una fundación local, este pabellón aloja talleres de oficios para jóvenes de la isla. Se levantó en seis meses con maderas certificadas de la región y un equipo de carpinteros locales. La cubierta inclinada recoge el agua lluvia hacia un tanque enterrado.",
        en: "Commissioned by a local foundation, this pavilion houses craft workshops for young people from the island. Built in six months with certified regional timber and a team of local carpenters. The pitched roof collects rainwater into a buried tank.",
      },
      gallery: [
        { tone: "olive", caption: { es: "Vista lateral entre los manglares", en: "Side view among the mangroves" } },
        { tone: "warm", caption: { es: "Estructura interior — encuentro de cerchas", en: "Interior structure — truss connection" } },
        { tone: "cream", caption: { es: "Taller en uso — clase de tejido", en: "Workshop in use — weaving class" } },
        { tone: "stone", caption: { es: "Detalle del pilotaje", en: "Stilt detail" } },
      ],
    },
    {
      id: "casa-tres-arboles",
      category: "architecture",
      featured: false,
      tone: "stone",
      title: { es: "Casa Tres Árboles", en: "Three Trees House" },
      subtitle: {
        es: "Una casa que se acomoda alrededor de un samán existente.",
        en: "A house that arranges itself around an existing rain tree.",
      },
      location: "Santa Marta, Magdalena",
      year: "2022",
      type: { es: "Vivienda unifamiliar", en: "Single-family house" },
      area: "260 m²",
      status: { es: "Construido", en: "Built" },
      role: { es: "Arquitecta principal", en: "Lead architect" },
      team: { es: "Laura Tejeda, Sara Pinzón", en: "Laura Tejeda, Sara Pinzón" },
      photos: "Federico Ríos",
      about: {
        es: "El cliente pidió una sola cosa: no tumbar el samán. La casa se desdobla en dos volúmenes que abrazan el árbol y crean un patio íntimo donde sucede la vida diaria.",
        en: "The client asked for one thing: don't fell the rain tree. The house unfolds into two volumes that embrace the tree and create an intimate courtyard where daily life happens.",
      },
      gallery: [
        { tone: "stone", caption: { es: "Patio bajo el samán", en: "Courtyard beneath the rain tree" } },
        { tone: "warm", caption: { es: "Volumen este — fachada poniente", en: "East volume — west façade" } },
        { tone: "cream", caption: { es: "Comedor abierto al patio", en: "Dining room open to the courtyard" } },
      ],
    },
    {
      id: "casa-marea",
      category: "architecture",
      featured: false,
      tone: "cool",
      title: { es: "Casa Marea", en: "Tide House" },
      subtitle: {
        es: "Refugio costero que cambia con las mareas.",
        en: "Coastal retreat that shifts with the tides.",
      },
      location: "Palomino, La Guajira",
      year: "2024",
      type: { es: "Vivienda de descanso", en: "Holiday home" },
      area: "180 m²",
      status: { es: "En obra", en: "In construction" },
      role: { es: "Arquitecta principal", en: "Lead architect" },
      team: { es: "Laura Tejeda, Mateo Ríos", en: "Laura Tejeda, Mateo Ríos" },
      photos: "—",
      about: {
        es: "Una casa elevada sobre la duna, hecha en estructura ligera para resistir la salinidad. Las terrazas escalonadas siguen el ritmo del oleaje y permiten dormir afuera en las noches secas.",
        en: "A house lifted on the dune, made of lightweight structure to resist salinity. Stepped terraces follow the wave rhythm and let you sleep outside on dry nights.",
      },
      gallery: [
        { tone: "cool", caption: { es: "Estado actual de obra", en: "Current construction state" } },
        { tone: "stone", caption: { es: "Maqueta 1:50", en: "1:50 model" } },
        { tone: "cream", caption: { es: "Render preliminar — terraza norte", en: "Preliminary render — north terrace" } },
      ],
    },
    {
      id: "biblioteca-sotavento",
      category: "architecture",
      featured: false,
      tone: "dark",
      title: { es: "Biblioteca Sotavento", en: "Sotavento Library" },
      subtitle: {
        es: "Pequeña biblioteca pública en un barrio del sur.",
        en: "A small public library in a southern neighbourhood.",
      },
      location: "Soledad, Atlántico",
      year: "2023",
      type: { es: "Equipamiento cultural", en: "Cultural facility" },
      area: "420 m²",
      status: { es: "Construido", en: "Built" },
      role: { es: "Co-autora con Estudio Tropical", en: "Co-author with Estudio Tropical" },
      team: { es: "Laura Tejeda, Estudio Tropical", en: "Laura Tejeda, Estudio Tropical" },
      photos: "Andrés Valbuena",
      about: {
        es: "Encargada por la alcaldía local, la biblioteca ocupa el lote de una antigua bodega. La fachada de bloques de cemento perforados crea un velo de luz que cambia durante el día.",
        en: "Commissioned by the local mayor's office, the library occupies the lot of a former warehouse. A perforated concrete-block façade creates a veil of light that changes through the day.",
      },
      gallery: [
        { tone: "dark", caption: { es: "Fachada al atardecer", en: "Façade at dusk" } },
        { tone: "warm", caption: { es: "Sala de lectura principal", en: "Main reading room" } },
        { tone: "stone", caption: { es: "Patio interior", en: "Interior patio" } },
      ],
    },

    // -------- INTERIORS --------
    {
      id: "apartamento-conde",
      category: "interiors",
      featured: true,
      tone: "cream",
      title: { es: "Apartamento Conde", en: "Conde Apartment" },
      subtitle: {
        es: "Un apartamento de los setenta, devuelto a su mejor versión.",
        en: "A 1970s apartment returned to its best self.",
      },
      location: "Bocagrande, Cartagena",
      year: "2024",
      type: { es: "Renovación residencial", en: "Residential renovation" },
      area: "165 m²",
      status: { es: "Construido", en: "Built" },
      role: { es: "Diseño de interiores y dirección", en: "Interior design & direction" },
      team: { es: "Laura Tejeda, Sara Pinzón", en: "Laura Tejeda, Sara Pinzón" },
      photos: "Federico Ríos",
      about: {
        es: "El apartamento estaba intervenido con muros que tapaban las vistas al mar. Demolimos lo necesario, recuperamos los pisos en granito original y diseñamos las piezas claves a medida: una biblioteca de cedro, una cocina abierta y una cama-mueble que organiza la habitación principal.",
        en: "The apartment had been chopped up with walls blocking the sea views. We demolished what was needed, recovered the original granite floors and designed the key pieces bespoke: a cedar library, an open kitchen and a bed-furniture that organises the main bedroom.",
      },
      gallery: [
        { tone: "cream", caption: { es: "Sala principal con vista a la bahía", en: "Main living room with bay view" } },
        { tone: "warm", caption: { es: "Biblioteca de cedro a medida", en: "Bespoke cedar library" } },
        { tone: "terracotta", caption: { es: "Cocina abierta — encimera de mármol", en: "Open kitchen — marble counter" } },
        { tone: "stone", caption: { es: "Habitación principal", en: "Main bedroom" } },
        { tone: "dark", caption: { es: "Baño en travertino", en: "Travertine bathroom" } },
      ],
    },
    {
      id: "restaurante-mestiza",
      category: "interiors",
      featured: true,
      tone: "clay",
      title: { es: "Restaurante Mestiza", en: "Mestiza Restaurant" },
      subtitle: {
        es: "Cocina caribeña en un local de 1920.",
        en: "Caribbean cuisine inside a 1920 storefront.",
      },
      location: "El Prado, Barranquilla",
      year: "2023",
      type: { es: "Restaurante", en: "Restaurant" },
      area: "210 m²",
      status: { es: "Abierto al público", en: "Open to the public" },
      role: { es: "Diseño de interiores", en: "Interior design" },
      team: { es: "Laura Tejeda, Mateo Ríos", en: "Laura Tejeda, Mateo Ríos" },
      photos: "Andrés Valbuena",
      about: {
        es: "Mestiza ocupa una casa republicana en El Prado. Conservamos los pisos en mosaico hidráulico originales y construimos sobre ellos: un bar largo en barro cocido, sillas de mimbre tejidas en Usiacurí y un techo de cañabrava que suaviza el ruido y la luz.",
        en: "Mestiza occupies a republican house in El Prado. We preserved the original hydraulic mosaic floors and built upon them: a long terracotta bar, wicker chairs woven in Usiacurí, and a cane ceiling that softens noise and light.",
      },
      gallery: [
        { tone: "clay", caption: { es: "Vista del salón principal", en: "Main dining room view" } },
        { tone: "warm", caption: { es: "Bar de barro cocido", en: "Terracotta bar" } },
        { tone: "cream", caption: { es: "Detalle del techo de cañabrava", en: "Cane ceiling detail" } },
        { tone: "dark", caption: { es: "Patio trasero al anochecer", en: "Back patio at dusk" } },
      ],
    },
    {
      id: "estudio-galería",
      category: "interiors",
      featured: false,
      tone: "stone",
      title: { es: "Estudio Galería 11", en: "Studio Gallery 11" },
      subtitle: {
        es: "Galería de arte de pequeño formato en una bodega del centro.",
        en: "Small-format art gallery in a downtown warehouse.",
      },
      location: "Centro, Barranquilla",
      year: "2024",
      type: { es: "Galería", en: "Gallery" },
      area: "140 m²",
      status: { es: "Abierto al público", en: "Open to the public" },
      role: { es: "Diseño de interiores y mobiliario", en: "Interior design & furniture" },
      team: { es: "Laura Tejeda", en: "Laura Tejeda" },
      photos: "Federico Ríos",
      about: {
        es: "Una bodega industrial transformada en sala expositiva. Conservamos las cerchas de hierro, blanqueamos los muros y diseñamos un sistema modular de pedestales en madera maciza.",
        en: "An industrial warehouse turned exhibition space. We kept the iron trusses, whitewashed the walls and designed a modular system of solid-wood pedestals.",
      },
      gallery: [
        { tone: "stone", caption: { es: "Sala principal con cerchas vistas", en: "Main hall with exposed trusses" } },
        { tone: "cream", caption: { es: "Sistema modular de pedestales", en: "Modular pedestal system" } },
        { tone: "warm", caption: { es: "Ingreso desde la calle", en: "Entrance from the street" } },
      ],
    },
    {
      id: "casa-malva",
      category: "interiors",
      featured: false,
      tone: "warm",
      title: { es: "Casa Malva", en: "Malva House" },
      subtitle: {
        es: "Una casa familiar reorganizada alrededor de la cocina.",
        en: "A family home reorganised around the kitchen.",
      },
      location: "Riomar, Barranquilla",
      year: "2022",
      type: { es: "Renovación residencial", en: "Residential renovation" },
      area: "240 m²",
      status: { es: "Construido", en: "Built" },
      role: { es: "Diseño de interiores", en: "Interior design" },
      team: { es: "Laura Tejeda", en: "Laura Tejeda" },
      photos: "Federico Ríos",
      about: {
        es: "La cocina, antes escondida al fondo de la casa, se trajo al centro y se convirtió en el corazón social. Una isla de cinco metros, un comedor pequeño que rota y una despensa abierta organizan la planta.",
        en: "The kitchen, once hidden at the back of the house, was brought to the centre and became the social heart. A five-metre island, a small rotating dining table and an open pantry organise the plan.",
      },
      gallery: [
        { tone: "warm", caption: { es: "Cocina-comedor", en: "Kitchen-dining" } },
        { tone: "cream", caption: { es: "Sala adyacente", en: "Adjacent living room" } },
        { tone: "terracotta", caption: { es: "Despensa abierta", en: "Open pantry" } },
      ],
    },
    {
      id: "tienda-corteza",
      category: "interiors",
      featured: false,
      tone: "olive",
      title: { es: "Tienda Corteza", en: "Corteza Store" },
      subtitle: {
        es: "Tienda de cerámica y oficios.",
        en: "Ceramics & craft store.",
      },
      location: "Getsemaní, Cartagena",
      year: "2023",
      type: { es: "Comercio", en: "Retail" },
      area: "60 m²",
      status: { es: "Abierto al público", en: "Open to the public" },
      role: { es: "Diseño de interiores y mobiliario", en: "Interior design & furniture" },
      team: { es: "Laura Tejeda", en: "Laura Tejeda" },
      photos: "Andrés Valbuena",
      about: {
        es: "Una tienda pequeña que también funciona como taller. El mostrador es una mesa de trabajo, las repisas son tablones de madera reciclada y la luz se cuela por una claraboya recuperada.",
        en: "A small store that also works as a workshop. The counter is a worktable, the shelves are reclaimed timber boards and the light filters through a recovered skylight.",
      },
      gallery: [
        { tone: "olive", caption: { es: "Vista desde la calle", en: "View from the street" } },
        { tone: "warm", caption: { es: "Mostrador y vitrina", en: "Counter and display" } },
      ],
    },
  ],

  services: [
    {
      n: "01",
      title: { es: "Arquitectura residencial", en: "Residential architecture" },
      body: {
        es: "Casas, ampliaciones y obra nueva. Desde el anteproyecto hasta la dirección de obra, con un calendario claro y un equipo pequeño que acompaña el proceso completo.",
        en: "Houses, extensions and new builds. From schematic design to construction direction, with a clear calendar and a small team that follows the whole process.",
      },
    },
    {
      n: "02",
      title: { es: "Interiorismo", en: "Interior design" },
      body: {
        es: "Renovación integral de espacios residenciales y comerciales. Diseño de mobiliario a medida, dirección de obra interior y curaduría de piezas artesanales.",
        en: "Full renovation of residential and commercial spaces. Bespoke furniture design, interior construction direction and curation of handmade pieces.",
      },
    },
    {
      n: "03",
      title: { es: "Diseño de mobiliario", en: "Furniture design" },
      body: {
        es: "Piezas únicas o pequeñas series, fabricadas con artesanos del Caribe colombiano: madera, cerámica, mimbre, hierro forjado.",
        en: "One-off pieces or small series, made with Colombian Caribbean artisans: wood, ceramic, wicker, wrought iron.",
      },
    },
    {
      n: "04",
      title: { es: "Consultoría", en: "Consulting" },
      body: {
        es: "Acompañamiento en etapas iniciales: lectura del lugar, programación, viabilidad y selección de equipos.",
        en: "Early-stage support: site reading, programming, feasibility and team selection.",
      },
    },
  ],

  process: [
    {
      n: "01",
      title: { es: "Conversación", en: "Conversation" },
      body: {
        es: "Una visita al lugar, dos horas de conversación y un cuaderno. Sin fórmulas. Salimos con un primer mapa de lo que pide el proyecto.",
        en: "A site visit, two hours of conversation, and a notebook. No formulas. We leave with a first map of what the project asks for.",
      },
      duration: { es: "2–3 semanas", en: "2–3 weeks" },
    },
    {
      n: "02",
      title: { es: "Anteproyecto", en: "Schematic design" },
      body: {
        es: "Plantas, cortes, una maqueta a escala y una primera paleta de materiales. Tres reuniones, tres iteraciones.",
        en: "Plans, sections, a scale model and a first material palette. Three meetings, three iterations.",
      },
      duration: { es: "6–10 semanas", en: "6–10 weeks" },
    },
    {
      n: "03",
      title: { es: "Proyecto técnico", en: "Construction documents" },
      body: {
        es: "Detalles constructivos, especificaciones, coordinación con ingenierías. Aquí el proyecto se vuelve buildable.",
        en: "Construction details, specs, engineering coordination. This is where the project becomes buildable.",
      },
      duration: { es: "8–12 semanas", en: "8–12 weeks" },
    },
    {
      n: "04",
      title: { es: "Obra y entrega", en: "Construction & delivery" },
      body: {
        es: "Visita semanal a obra, control de calidad, dirección artística. Acompañamos hasta el último mueble entregado.",
        en: "Weekly site visits, quality control, art direction. We stay until the last piece of furniture is delivered.",
      },
      duration: { es: "Variable", en: "Variable" },
    },
  ],

  press: [
    { source: "Axxis", year: "2024", title: { es: "Casa Palmar — el regreso del patio", en: "Palmar House — the return of the courtyard" } },
    { source: "Wallpaper* LATAM", year: "2024", title: { es: "10 estudios jóvenes del Caribe", en: "10 young studios from the Caribbean" } },
    { source: "Bienal Colombiana", year: "2023", title: { es: "Mención en vivienda", en: "Housing mention" } },
    { source: "Diseño Interior", year: "2023", title: { es: "Mestiza, la cocina como lugar", en: "Mestiza, kitchen as place" } },
  ],
};
